name: Runner Preparation

on:
  workflow_call:
    outputs:
      matrix-NVIDIA:
        value: ${{ jobs.prepare.outputs.matrix-NVIDIA }}
      matrix-AMD:
        value: ${{ jobs.prepare.outputs.matrix-AMD }}
      matrix-MACOS:
        value: ${{ jobs.prepare.outputs.matrix-MACOS }}
      matrix-PPU:
        value: ${{ jobs.prepare.outputs.matrix-PPU }}

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix-NVIDIA: ${{ steps.set-matrix.outputs.matrix-NVIDIA }}
      matrix-AMD: ${{ steps.set-matrix.outputs.matrix-AMD }}
      matrix-MACOS: ${{ steps.set-matrix.outputs.matrix-MACOS }}
      matrix-PPU: ${{ steps.set-matrix.outputs.matrix-PPU }}
    steps:
      - name: Decide pre-submit integration test enablement
        # Always enable integration tests for pre-submit pull requests.
        if: github.event_name == 'pull_request'
        run: |
          echo "enable_integration=true" >> $GITHUB_ENV
      - name: Decide manual trigger integration test enablement
        # Always enable integration tests when manually triggered
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "enable_integration=true" >> $GITHUB_ENV
      - name: Checkout post-submit commits
        if: github.event_name == 'push'
        uses: actions/checkout@v5
        with:
          # Only fetch two commits to check the latest changed files.
          fetch-depth: 2
      - name: Detect if build deps (e.g. LLVM hash) changed
        id: detect-change
        if: github.event_name == 'push'
        uses: tj-actions/changed-files@v47
        with:
          files: |
            cmake/*.txt
            cmake/*.json
      - name: Decide whether to run integration tests post-submit
        if: github.event_name == 'push'
        run: |
          echo "enable_integration=true" >> $GITHUB_ENV
      - name: Prepare runner matrix
        id: set-matrix
        if: env.enable_integration == 'true'
        run: |
          if [ x"${{ github.repository }}" == x"triton-lang/triton" ]; then
            echo '::set-output name=matrix-NVIDIA::[["nvidia-a100"], ["nvidia-h100"], ["nvidia-gb200"]]'
            echo '::set-output name=matrix-AMD::[["self-hosted", "gfx90a"], ["amd-gfx942"], ["amd-gfx950"]]'
            echo '::set-output name=matrix-MACOS::[["macos-latest"]]'
          else
            # TODO: Enable NVIDIA/AMD/macOS CI when runners are available
            # echo '::set-output name=matrix-NVIDIA::["ubuntu-latest"]'
            # echo '::set-output name=matrix-AMD::["ubuntu-latest"]'
            # echo '::set-output name=matrix-MACOS::["macos-latest"]'
            # PPU CI enabled: run in parallel on 890P and 810E boards
            echo '::set-output name=matrix-PPU::["ZW-M890P", "OAM-810E"]'
          fi
